### ISSUE TITLE
Status Icon

### ISSUE THREAD

**Issue by PonyOny** [jneilliii/OctoPrint-Tasmota#2]
When I enter Octoprint, I can se the power indicator, and if it's off it goes 1 second red and then goes gray again, if it's green the same thing happens, it goes green then gray, clicking on the power icon does not work, it randomly works some times,  when clicking i'm getting a 204 No Content, if i execute the comand directly from the browser the unit works, but from OctoPrint it works sometimes only.
![screenshot_1](https://user-images.githubusercontent.com/17080292/33212409-4c20245a-d123-11e7-8205-1d9573f89fef.png)

**Comment by jneilliii** [comment]
The current state is probably getting out of sync with the tasmota is you're controlling outside of octoprint. What happens if you restart octoprint and ctrl+f5 to reload the page ignoring cache. Does it work then? Enable debugging and seeing logs would help too.

**Comment by PonyOny** [comment]
I have tried that, reloading & hiting F5 & disabling cache, same problem, disabling plugin & removing switch and adding it again seemed to do the trick but it seems it gets out of sync in some point, I have debugging active, here yo have the log file.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1501922/plugin_tasmota_debug.log)

**Comment by jneilliii** [comment]
That is strange, it definitely seems to be working.  Curious when it becomes out of sync. If you happen to notice let me know, but I have not experienced that myself. Because the plugin only uses web commands and not MQTT subscription it's not going to detect state changes outside of octoprint. I was trying to keep it as simple as possible and not require configuring a MQTT server, etc. Also, check the octoprint.log for any errors.

**Comment by PonyOny** [comment]
I will try to have a look if I can find how to reproduce this issue, doesn't it check every X time the status in case the switch has changed externally? I know it's html based and has no MQTT subscription, but i thought it might check every X to retrive current status, that should fix out of sync issues.

**Comment by jneilliii** [comment]
It currently does not do that timer check of state, but that could be a way to get around this specific issue.  I just pushed some changes to the dev branch to enhance the console logging on the client and server sides.  While doing so, I think I may found the issue.  I wasn't saving the settings outside ot the switch and it was only saving on an unknown state. You may have better results now with this version. If you don't mind letting me know and if it's working I can push to master.  Out of curiosity, how did you find this plugin?

Install via plugin manager using this url: https://github.com/jneilliii/OctoPrint-Tasmota/archive/dev.zip

**Comment by PonyOny** [comment]
I will give that a try, lets see :), I discovered this plugin looking for sonoff integration with octoprint and your project apeared in google, I can see you have the Tplink switch on the plugins search in octoprint but not this one.
I will install the dev version and will try if it has better response, thanks for quick answer & fix.

**Comment by PonyOny** [comment]
I have tested it and it seems more responsful, the icons are updating correctly and after reboot the status icon is the correct one, I will keep testing it during this days.

BTW: I supose this plugin is still not published to ¨production¨ i have seen there are some texts  from the TPLink plugin, I supose you made a copy of the other one and adapted it to Sonoff and have not changed the descriptions yet.
<img width="754" alt="screenshot_1" src="https://user-images.githubusercontent.com/17080292/33222285-4a0c8bd0-d156-11e7-8964-898b326d4c92.png">

**Comment by jneilliii** [comment]
Good news on it working better now. You are right, I based this on my original tplink plugin from a user request to control sonoff devices. Before that didn't even know anything about them. I could see benefits, especially with multi relay versions for controlling lights, fans,  etc.

**Comment by PonyOny** [comment]
Hi, this morning i have connected remotly to my Octoprint, the status of the tasmota was red because it was off, I have clicked the icon to enable it and that went fine, it turned on the power, I did a print and after 2h I entered Octoprint and icon was spitting out connection issues and I connected to tasmota ip and it was ok, the plugin stoped comunicating with it, I have seen that the ip in my case has a final  . i dont know if this is a log issue or maybe some bug in code that addeed an extra . to the end of the ip, I am ataching the log so you can se when it was off then turned it on and the connection lost.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/1503112/plugin_tasmota_debug.log)

**Comment by PonyOny** [comment]
![Image](https://i.imgur.com/qFXdoHN.jpg)
As you can see here in the screen shot and in the logs you can see that the ip is 192.168.1.35. With that extra “.” at the end, maybe it’s only visual but it’s strange it cant connect to the Ip, if you navigate to the ip it displays correctly the tasmota menu and http commands work fine through browser/Postman.

**Comment by jneilliii** [comment]
I'll check out the logs, but the periods are for terminating the end of a sentence, not ferrying used for communication.

**Comment by jneilliii** [comment]
Any chance the ip of your octoprint changed to a different network that doesn't have the same access as the machine you're able to get to the tasmota device from? Are there any errors in the debug console of your browser or in octoprint.log?

**Comment by PonyOny** [comment]
Holy Cow just saw what happened, I have multiple wifi points in my house and octopi switched to another acces point, same network etc.. but it’s a tplink issue with conections to the repeater not beeing able to comunicate to other devices conected to the main router, I have restricted acces points to dissalau octoprint to switch between points and comunication flows again :) now it detects & works propperly.

**Comment by jneilliii** [comment]
Awesome, was hoping it was something like that and not the plugin.

**Comment by jneilliii** [comment]
FYI...the plugin was merged into the plugin repository.
